### ISSUE TITLE
Bug in publishcv.sh

### ISSUE THREAD

**Issue by boogiespook** [RedHatEMEA/soe-ci#13]
Hi Nick,

Just noticed a bug in publishcv.sh.

"hammer content-view version promote --content-view \"${CV}\" --organization \"${ORG}\" \
    --lifecycle-environment-id \"${TESTVM_ENV}\" --id ${VER}"

Should read:
"hammer content-view version promote --content-view \"${CV}\" --organization \"${ORG}\" \
    --to-lifecycle-environment-id \"${TESTVM_ENV}\" --id ${VER}"

Perhaps this changed in v 6.0.6?

  Chris

**Comment by nstrug** [comment]
Hi Chris -

If you have a patch I'll accept the pull request.

Cheers,
Nick

**Comment by evgeni** [comment]
This was changed in hammer 0.0.5, but we ship 0.0.4 in Sat6.
https://github.com/Katello/hammer-cli-katello/commit/8958e24eb5486c978c6cbdf172c6a04376e2bf43

Not sure how to handle this properly.

**Comment by evgeni** [comment]
One could use the following to differentiate the versions

    hammer --version | grep hammer_cli_katello | sed 's#.*(\(.*\)).*#\1#'

But I probably would refuse such code in my own projects.

**Comment by nstrug** [comment]
Fixed in https://github.com/RedHatEMEA/soe-ci/commit/4fa1febfd2c37bf254bea9bf3c19541a2ea23b72
