### ISSUE TITLE
[Question] This looks simple for single group of team

### ISSUE THREAD

**Issue by dhajoshi** [RedHatEMEA/soe-ci#18]
Hello,

how about multiple teams working on different projects (for example we have 100 diff teams working on diff projects ), we created multiple products for them in satellite and repos for them, now issue is .. for a particular consumer you can only bind single content view, if App1 wants to use product or repo from App2 they have to add their repos to App1's content view (but you cant simple assign 2 CV to a particular system).

how to segregate OS related repos and application repos?, so for example if we update OS repo for some erratas, we can just update CV for OS repos only and App CVs are different, but problem is only one CV can be assigned to particular host

Regards,
DJ

**Comment by nstrug** [comment]
This is what Composite Content Views are for. You would have separate build plans for each product:
* Base Infra (OS + infra apps, monitoring, security etc)
* Product A
* Product B
Each product is built separately.
Then you would break out the testing phase into separate build plans, dependant on successful building of the sub-products. Each test build plan would assemble a CCV, deploy test servers, and test them for the infra+product combination.

**Comment by dhajoshi** [comment]
Thanks for your answer, this is what my infra looks like. https://access.redhat.com/discussions/1335473

**Comment by nstrug** [comment]
going to close the issue as this isn't the right forum to discuss Red Hat customer issues - will discuss offline.
