### ISSUE TITLE
RHEL mock config files need a note for baseurl

### ISSUE THREAD

**Issue by pcfe** [RedHatEMEA/soe-ci#31]
please add a note to both mock config files and the readme.
The user does not only need to take the cert and key from their existing /etc/yum.repos.d/redhat.repo but also the baseurl

**Comment by ericzolf** [comment]
@pcfe did here a smart thing: his Jenkins build server points to the Satellite instead of having a direct connection to CDN. Something to consider as well for the reference setup.
